version: "3.8"

services:
  app:
    image: zarqeon/hass-lovelace-kindle-screensaver:latest
    environment:
      - HA_BASE_URL=https://your-path-to-home-assistant:8123
      - HA_SCREENSHOT_URL=/lovelace?kiosk
      - HA_ACCESS_TOKEN=eyJ0...
      - CRON_JOB=* * * * *
      - RENDERING_TIMEOUT=30000
      - RENDERING_DELAY=0
      - RENDERING_SCREEN_HEIGHT=800
      - RENDERING_SCREEN_WIDTH=600
      - GRAYSCALE_DEPTH=8
      - OUTPUT_PATH=/output/cover.png
      - LANGUAGE=en
      - ROTATION=0
      - SCALING=1
    ports:
      - 5000:5000
    volumes:
      - ./output/:/output
